language: "node_js"
node_js:
  - "10"
  - "12"
  - "14"
  - "15"
branches:
  only:
    - main
script:
  - npm test
after_success:
  - npm i coveralls -D
  - node node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
